service: multi-lang-microservices
frameworkVersion: "3"

provider:
  name: aws
  runtime: custom
  ecr:
    images:
      goLangMicroService:
        path: ./goLang
      javascriptMicroService:
        path: ./javaScript
      pythonMicroService:
        path: ./python

functions:
  jsIsolatedFunction: # Use specific routes to override your Micro-service when you need a custom Memory/ CPU env for one endpoint only
    runtime: nodejs20.x
    memorySize: 512
    handler: ./IsolatedJS/index.handler
    events:
      - httpApi:
          path: /js/api/isolated
          method: GET
  jsMicroservice:
    image:
      name: javascriptMicroService
    events:
      - httpApi:
          path: /js/{proxy+}
          method: ANY
  pythonMicroservice:
    image:
      name: pythonMicroService
    events:
      - httpApi:
          path: /py/{proxy+}
          method: ANY
  goLangMicroservice:
    image:
      name: goLangMicroService
    events:
      - httpApi:
          path: /go/{proxy+}
          method: ANY
